### ISSUE TITLE
This run is a little slow. The optimized version has been completed.

### ISSUE THREAD

**Issue by aizhiqi-work** [gusrud1103/LibriPhrase#2]
Send it to the GitHub repository later.

**Comment by aizhiqi-work** [comment]
Does anyone continue to do this technical route?

**Comment by XiYu-uuu** [comment]
Do you know how to generate the same LS_{E} and LS_{H} mentioned in the paper to evaluate the performance?  just run run.sh?

> Does anyone continue to do this technical route?

**Comment by aizhiqi-work** [comment]
交大盆友，中文回复。论文的这个方法是可以根据他历程生成的正例/负例数据的。训练集460h，测试用的other500. 会生成一大批正例负例难例csv和audio。但是整体速度确实还是慢的。你最近还在关注这个技术路线吗
